quarkus:
  datasource:
    db-kind: postgresql
  hibernate-orm:
    database:
      generation: update
  oidc:
    client-id: azide
    application-type: web-app
  http:
    auth:
      permission:
        authenticated:
          paths: /app/*
          policy: authenticated
classificationBanner: 
  classification: UNCLASSIFIED - FOR TESTING PURPOSES ONLY
  color: "#007a33"
"%dev":
  quarkus:
    log:
      level: DEBUG
    hibernate-orm:
      database:
        generation: drop-and-create
  applicationInfo:
    applications:
      - name: App 1
        location: "#App1"
        image: /res/media/gazebo-1.jpg
      - name: App 2
        location: "#App2"
        image: /res/media/gazebo-1.jpg
      - name: App 3
        location: "#App3"
        image: /res/media/gazebo-1.jpg