

quarkus:
  datasource:
    db-kind: postgresql
  hibernate-orm:
    database:
      generation: update
  oidc:
    client-id: azide
    application-type: web-app
  http:
    auth:
      permission:
        authenticated:
          paths: /*
          policy: authenticated
"%dev":
  quarkus:
    log:
      level: DEBUG
    hibernate-orm:
      database:
        generation: drop-and-create
  providedSites:
    sites:
    - title: Google
      description: It's Google
      url: https://google.com