quarkus:
  datasource:
    db-kind: postgresql
  hibernate-orm:
    database:
      generation: update
  oidc:
    client-id: azide
    application-type: web-app
    logout:
      path: /logout
      post-logout-path: /
  http:
    auth:
      permission:
        authenticated:
          paths: /app/*
          policy: authenticated
classificationBanner: 
  classification: UNCLASSIFIED - FOR TESTING PURPOSES ONLY
  color: "#007a33"
"%dev":
  quarkus:
    log:
      level: DEBUG
    hibernate-orm:
      database:
        generation: drop-and-create
  applicationInfo:
    applications:
      - name: Msg Viewer
        location: "/app/viewer/message-viewer"
        image: /res/media/gazebo-1.jpg
        showInAppBar: true
      - name: Msg Editor
        location: "/app/viewer/message-editor"
        image: /res/media/gazebo-1.jpg
        showInAppBar: false
      - name: Google
        location: "https://www.google.com"
        image: /res/media/gazebo-3.jpg
        showInAppBar: true