quarkus:
  datasource:
    db-kind: postgresql
  hibernate-orm:
    database:
      generation: update
  oidc:
    client-id: azide
    application-type: web-app
    logout:
      path: /logout
      post-logout-path: /
  http:
    auth:
      permission:
        logout:
          paths: ${quarkus.oidc.logout.path}
          policy: authenticated
classificationBanner: 
  classification: UNCLASSIFIED - FOR TESTING PURPOSES ONLY
  color: "#007a33"
"%dev":
  quarkus:
    log:
      level: DEBUG
    hibernate-orm:
      database:
        generation: drop-and-create
  applicationInfo:
    applications:
      - name: Msg Viewer
        reference: msgs
        description: "This is the Message Viewer"
        location: "http://localhost:8081/messages"
        showInAppBar: true
        defaultApp: true
        splashApp: true
        splashEndpoint: "http://localhost:8081/messages"