quarkus:
  datasource:
    db-kind: postgresql
  hibernate-orm:
    database:
      generation: update
  oidc:
    client-id: azide
    application-type: web-app
    logout:
      path: /logout
      post-logout-path: /
  http:
    auth:
      permission:
        logout:
          paths: ${quarkus.oidc.logout.path}
          policy: authenticated
  container-image:
    group: "dcgs"
classificationBanner:
  classification: UNCLASSIFIED - FOR TESTING PURPOSES ONLY
  color: "#007a33"
service:
  aupText: >
    Welcome to our Acceptable Use Policy (AUP) page. By using our service, you agree to the following terms...
applicationInfo:
  applications:

"%dev":
  quarkus:
    log:
      level: DEBUG
    hibernate-orm:
      database:
        generation: drop-and-create
#    oidc:
#      # Get this from config debug output from Azide
#      auth-server-url: http://localhost:8085/realms/quarkus
#      client-id: azide
#      credentials:
#        secret: "secret"
  applicationInfo:
    applications:
      # Lots of applications
      - name: Dev App
        reference: dev-app
        location: /dev/app?testAppRef=dev-app
        showInAppBar: true
        image: /dev/app/image?testAppRef=dev-app
        description: "Development app for testing things"
        defaultApp: false
        splashApp: false
        splashEndpoint: /dev/app?testAppRef=dev-app
#      - name: Landing Page
#        reference: landing-page
#        location: http://localhost:8081
#        showInAppBar: true
#        image: "/res/media/dcgsalogo.png"
#        description: "Landing Page"
#        defaultApp: false
#        splashApp: false
#        splashEndpoint: http://localhost:8081
#      - name: Test Data Viewer
#        reference: testdataviewer
#        location: http://localhost:8082
#        image: "/res/media/dcgsalogo.png"
#        showInAppBar: true
#        description: "Test Data Viewer for testing cross app communications"
#        splashApp: false
#      - name: Test Data Generator
#        reference: testdatagenerator
#        location: http://localhost:8083
#        image: "/res/media/dcgsalogo.png"
#        showInAppBar: true
#        description: "Test Data Generator for testing cross app communications"
#        splashApp: false