quarkus:
  datasource:
    db-kind: postgresql
  hibernate-orm:
    database:
      generation: update
  oidc:
    client-id: azide
    application-type: web-app
    logout:
      path: /logout
      post-logout-path: /
  http:
    auth:
      permission:
        logout:
          paths: ${quarkus.oidc.logout.path}
          policy: authenticated
classificationBanner:
  classification: UNCLASSIFIED - FOR TESTING PURPOSES ONLY
  color: "#007a33"
service:
  aupText: >
    Welcome to our Acceptable Use Policy (AUP) page. By using our service, you agree to the following terms...
applicationInfo:
  applications:

"%dev":
  quarkus:
    oidc:
      auth-server-url: http://locahost:8085/realms/quarkus
      credentials:
        secret: "secret"
    log:
      level: DEBUG
    hibernate-orm:
      database:
        generation: drop-and-create
    oidc:
      # Get this from config debug output from Azide
      auth-server-url: http://localhost:8085/realms/quarkus
      client-id: azide
      credentials:
        secret: "**********"
  applicationInfo:
    applications:
      # Need to update/ run messages app after Azide runs, and get dev oidc resources
      #      - name: Messages App
      #        reference: messages-app
      #        location: http://localhost:8082
      #        showInAppBar: true
      #        description: "Messages App for showing messages."
      #        defaultApp: true
      #        splashApp: true
      #        splashEndpoint: http://localhost:8082
      
      
      # Lots of applications
      - name: Test Image 1
        reference: testImage1
        location: "/res/media/dcgsalogo.png"
        image: "/res/media/dcgsalogo.png"
        showInAppBar: true
        description: "Test image as an app."
      - name: Test Image 2
        reference: testImage2
        location: "/res/media/dcgsalogo.png"
        image: "/res/media/dcgsalogo.png"
        showInAppBar: true
        description: "Test image as an app."
#      - name: Test Image3
#        reference: testImage3
#        location: "/res/media/dcgsalogo.png"
#        image: "/res/media/dcgsalogo.png"
#        showInAppBar: true
#        description: "Test image as an app."
#      - name: Test Image4
#        reference: testImage4
#        location: "/res/media/dcgsalogo.png"
#        image: "/res/media/dcgsalogo.png"
#        showInAppBar: true
#        description: "Test image as an app."
#      - name: Test Image5
#        reference: testImage5
#        location: "/res/media/dcgsalogo.png"
#        image: "/res/media/dcgsalogo.png"
#        showInAppBar: true
#        description: "Test image as an app."
#      - name: Test Image6
#        reference: testImage6
#        location: "/res/media/dcgsalogo.png"
#        image: "/res/media/dcgsalogo.png"
#        showInAppBar: true
#        description: "Test image as an app."
#      - name: Test Image7
#        reference: testImage7
#        location: "/res/media/dcgsalogo.png"
#        image: "/res/media/dcgsalogo.png"
#        showInAppBar: true
#        description: "Test image as an app."
#      - name: Test Image8
#        reference: testImage8
#        location: "/res/media/dcgsalogo.png"
#        image: "/res/media/dcgsalogo.png"
#        showInAppBar: true
#        description: "Test image as an app."
#      - name: Test Image9
#        reference: testImage9
#        location: "/res/media/dcgsalogo.png"
#        image: "/res/media/dcgsalogo.png"
#        showInAppBar: true
#        description: "Test image as an app."
#      - name: Test Image10
#        reference: testImage10
#        location: "/res/media/dcgsalogo.png"
#        image: "/res/media/dcgsalogo.png"
#        showInAppBar: true
#        description: "Test image as an app."
#      - name: Test Image11
#        reference: testImage11
#        location: "/res/media/dcgsalogo.png"
#        image: "/res/media/dcgsalogo.png"
#        showInAppBar: true
#        description: "Test image as an app."
#      - name: Test Image12
#        reference: testImage12
#        location: "/res/media/dcgsalogo.png"
#        image: "/res/media/dcgsalogo.png"
#        showInAppBar: true
#        description: "Test image as an app."
#      - name: Test Image13
#        reference: testImage13
#        location: "/res/media/dcgsalogo.png"
#        image: "/res/media/dcgsalogo.png"
#        showInAppBar: true
#        description: "Test image as an app."
#      - name: Test Image14
#        reference: testImage14
#        location: "/res/media/dcgsalogo.png"
#        image: "/res/media/dcgsalogo.png"
#        showInAppBar: true
#        description: "Test image as an app."
#      - name: Test Image15
#        reference: testImage15
#        location: "/res/media/dcgsalogo.png"
#        image: "/res/media/dcgsalogo.png"
#        showInAppBar: true
#        description: "Test image as an app."
