quarkus:
  datasource:
    db-kind: postgresql
  hibernate-orm:
    database:
      generation: update
  oidc:
    client-id: azide
    application-type: web-app
  http:
    auth:
      permission:
        authenticated:
          paths: /app/*
          policy: authenticated
classificationBanner: 
  classification: UNCLASSIFIED - FOR TESTING PURPOSES ONLY
  color: "#007a33"
"%dev":
  quarkus:
    log:
      level: DEBUG
    hibernate-orm:
      database:
        generation: drop-and-create